spring:
  application:
    name: customerservice
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8001
      profile: dev
      label: main
  datasource:
    hikari:
      connection-timeout=30000
      maximum-pool-size=10