spring:
  application:
    name: eureka
  cloud:
    config:
      uri: http://configserver:8001

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/