spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://configserver:8001
    loadbalancer:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: customer-service.routing
            uri: lb://customerservice
            predicates:
              - Path=/api/customers/**
          - id: product-service.routing
            uri: lb://productservice
            predicates:
              - Path=/api/products/**
          - id: identity-service.routing
            uri: lb://identityservice
            predicates:
              - Path=/api/auths/**
          - id: eureka.routing
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka.static-files
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/**
server:
  port: 8090

eureka:
  url: http://eureka:8888
  instance:
    hostname: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
