spring:
  application:
    name: identityservice
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db?sslmode=disable
    username: admin
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  instance:
    hostname: identityservice
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://identityservice:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
